### ISSUE TITLE
error while importing express

### ISSUE THREAD

**Issue by davideghz** [reactjs/react-router-tutorial#168]
Hi, I got an error importing express.
My server.js looks like the one in the repo.

The app works fine but it doesn't render source code on server

`
/server.js:1
(function (exports, require, module, __filename, __dirname) { import * as express from 'express'
                                                                                                  ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

`

How can I fix this? I'm on Ubuntu

**Comment by davideghz** [comment]
well.. I missed the update to package.json - I updated it as described and now I do not get errors in the terminal, but log errors in the browser console

`bundle.js:24 [WDS] Disconnected!`

and

```
Failed to load resource: http://localhost:8080/sockjs-node/info?t=1462899750885
the server responded with a status of 404 (Not Found)
```

**Comment by davideghz** [comment]
the error was still in `package.json` - I updated it to be exactly as per the repo version and now it works. ^^
