### ISSUE TITLE
Npm start fails on my system

### ISSUE THREAD

**Issue by mnemanja** [reactjs/react-router-tutorial#171]
Most likely related to this closed [issue](https://github.com/reactjs/react-router-tutorial/issues/164), but in my case I'm not running any other server that would occupy that port.
It fails with this as a problem `webpack-dev-server --inline --content-base`.
This was a clean install of the react router tutorial, npm install went fine, and after trying to execute  `npm start` the problem occurred.

My node version is 4.2.1 and npm is 3.5.2.

```
> tutorial@1.0.0 start C:\www\react\react-router-tutorial\lessons\01-setting-up
> webpack-dev-server --inline --content-base .

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nemanja.Milosavljevi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.1
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! tutorial@1.0.0 start: `webpack-dev-server --inline --content-base .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tutorial@1.0.0 start script 'webpack-dev-server --inline --content-base .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tutorial package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --content-base .
```

**Comment by MrOutis** [comment]
`Error: listen EACCES 127.0.0.1:8080`
This means that localhost at port 8080 is busy, so you can open the package.json and  `--port 7531` to the start script.

Now, you need to open localhost:7531 instead of 8080

**Comment by timdorr** [comment]
@MrOutis is correct. Something is already running on port 8080 on your system. You should stop that process so that webpack can run.
