### ISSUE TITLE
Lesson 3 "npm start" gives an error in ./index.js

### ISSUE THREAD

**Issue by tychovk** [reactjs/react-router-tutorial#174]
Hi guys,

See log below. I have no clue what the problem is. Any ideas? I cloned the repo and didn't change anything yet.

```
....etc
   [73] (webpack)-dev-server/~/strip-ansi/~/ansi-regex/index.js 135 bytes {0} [built]

ERROR in ./index.js
Module build failed: SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\dropbox\react-router-tutorial\lessons\03-navigating-with-link\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-template-literals\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.array.iterator.js:11:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
 @ multi main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
Hash: 67820962463f1da85d0c
Version: webpack 1.13.0
Time: 52ms
chunk    {0} bundle.js (main) 214 kB
     + 74 hidden modules

ERROR in ./index.js
Module build failed: SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\dropbox\react-router-tutorial\lessons\03-navigating-with-link\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-template-literals\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.array.iterator.js:11:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
 @ multi main
webpack: bundle is now VALID.
```

**Comment by tychovk** [comment]
I cloned the repo again somewhere else, and now it works. I don't have any idea what the case was... =/.
