### ISSUE TITLE
01lesson ,who can help me~? 

### ISSUE THREAD

**Issue by zengqiang24** [reactjs/react-router-tutorial#206]
npm start

> tutorial@1.0.0 start /Users/qiangzeng/react-router-tutorial/lessons/01-setting-up
> webpack-dev-server --inline --content-base .

module.js:327
    throw err;
    ^

Error: Cannot find module 'assert/'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at Object.<anonymous> (/Users/qiangzeng/react-router-tutorial/lessons/01-setting-up/node_modules/webpack/node_modules/node-libs-browser/index.js:1:93)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/qiangzeng/react-router-tutorial/lessons/01-setting-up/node_modules/webpack/lib/node/NodeSourcePlugin.js:7:23)

**Comment by zengqiang24** [comment]
sorry,I have already  solved the problem , please closed.

**Comment by DylanThomson** [comment]
Next time could you share your solution instead of closing it.
