### ISSUE TITLE
Lesson 1 - Error in webpack loaders

### ISSUE THREAD

**Issue by balnix** [reactjs/react-router-tutorial#208]
In lesson 01 after`npm install` and `npm start` I get an error:

ERROR in ./index.js

Module build failed: Error: Couldn't find preset "es2015" relative to directory "~"

    at ~/learn/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:313:17
    at Array.map (native)
    at OptionManager.resolvePresets (~/learn/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
    at OptionManager.mergePresets (~/learn/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:10)
    at OptionManager.mergeOptions (~/learn/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14)
    at OptionManager.init (~/learn/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:360:12)
    at File.initOptions (~/learn/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (~/learn/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (~/learn/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (~/learn/react-router-tutorial/lessons/01-setting-up/node_modules/babel-loader/index.js:14:22)
 @ multi main
webpack: bundle is now VALID.

**Comment by balnix** [comment]
This error appear if there is no es2015 in .baberc files
