### ISSUE TITLE
[Lesson-13]  webpack.server.config.js  error

### ISSUE THREAD

**Issue by FattyLiu** [reactjs/react-router-tutorial#222]
Great tutorial! Thank you :)

I found something wrong in lesson 13. I keep getting the error:

```
Production Express server running at localhost:8080
TypeError: path must be absolute or specify root to res.sendFile
    at ServerResponse.sendFile (/Users/liuchao/Documents/Code/react-router-tutorial/lessons/13-server-rendering/node_modules/express/lib/response.js:404:11)
    at /Users/liuchao/Documents/Code/react-router-tutorial/lessons/13-server-rendering/server.bundle.js:62:8
    at Layer.handle [as handle_request] (/Users/liuchao/Documents/Code/react-router-tutorial/lessons/13-server-rendering/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/liuchao/Documents/Code/react-router-tutorial/lessons/13-server-rendering/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/liuchao/Documents/Code/react-router-tutorial/lessons/13-server-rendering/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/liuchao/Documents/Code/react-router-tutorial/lessons/13-server-rendering/node_modules/express/lib/router/layer.js:95:5)
    at /Users/liuchao/Documents/Code/react-router-tutorial/lessons/13-server-rendering/node_modules/express/lib/router/index.js:277:22
    at param (/Users/liuchao/Documents/Code/react-router-tutorial/lessons/13-server-rendering/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/liuchao/Documents/Code/react-router-tutorial/lessons/13-server-rendering/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/liuchao/Documents/Code/react-router-tutorial/lessons/13-server-rendering/node_modules/express/lib/router/index.js:410:3)
```

It seems that `__dirname` is not found when trying to send file.

But I found if change file "webpack.server.config.js" like this:
```js
node: {
    __filename: false,
    __dirname: false
  },
```

then everything will be fine.

I use:
- node v6.2.2  
- npm v3.9.5
- webpack v1.12.13

I don't speak English so if there is somewhere I said wrong please don't mind.

**Comment by timdorr** [comment]
Without seeing the line of code you have that's causing the error, it's hard to see what's going on there. However, you should have the exact same code that is in lesson 14. If you have some difference, that's what's causing your error.
