### ISSUE TITLE
Lesson 13 - Clean urls do not work. http://localhost:8080/about returns Internal server error

### ISSUE THREAD

**Issue by jazzominy** [reactjs/react-router-tutorial#272]
After setting NODE_ENV to production and running `npm start`, the server (server.bundle.js) returns "Internal server error" when accessing any url (e.g. http://localhost:8080/about) apart from http://localhost:8080.
The console displays this error

    TypeError: path must be absolute or specify root to res.sendFile
    at ServerResponse.sendFile (D:\Jazz\nodeWS\react-router-tutorial\lessons\13-server-rendering\node_modules\express\lib\response.js:404:11)
    at D:\Jazz\nodeWS\react-router-tutorial\lessons\13-server-rendering\server.bundle.js:66:8
    at Layer.handle [as handle_request] (D:\Jazz\nodeWS\react-router-tutorial\lessons\13-server-rendering\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Jazz\nodeWS\react-router-tutorial\lessons\13-server-rendering\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\Jazz\nodeWS\react-router-tutorial\lessons\13-server-rendering\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Jazz\nodeWS\react-router-tutorial\lessons\13-server-rendering\node_modules\express\lib\router\layer.js:95:5)
    at D:\Jazz\nodeWS\react-router-tutorial\lessons\13-server-rendering\node_modules\express\lib\router\index.js:277:22
    at param (D:\Jazz\nodeWS\react-router-tutorial\lessons\13-server-rendering\node_modules\express\lib\router\index.js:349:14)
    at param (D:\Jazz\nodeWS\react-router-tutorial\lessons\13-server-rendering\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (D:\Jazz\nodeWS\react-router-tutorial\lessons\13-server-rendering\node_modules\express\lib\router\index.js:410:3)

The same url (http://localhost:8080/about) works when running server from `server.js`

I am not sure why this is happening

**Comment by jazzominy** [comment]
I found the issue. In `server.bundle.js`, the value of `__dirname` is not getting passed. So if `res.sendFile()` does not get absolute path, the about error is thrown.

The solution to this is use
`path.resolve(__dirname, 'public', 'index.html')` instead of 
`path.join(__dirname, 'public', 'index.html')` in `server.js`
