### ISSUE TITLE
Few details to make it perfect :)

### ISSUE THREAD

**Issue by yormi** [reactjs/react-router-tutorial#80]
Hi folks,

First of all, i think you should add a .babelrc with `{   presets: ['es2015'] }` . Unless I missed something it doesn't work without.

Secondly, `onSubmit={this.handleSubmit}` should be `onSubmit={this.handleSubmit.bind(this)}`. otherwise, `this` will be null in handleSubmit and there will be a null error when trying to get this.context.router
 
Thanks for the tutorial guys ! It's awesome !

EDIT: I just saw the preset in webpack.config.js but it didn't do the trick apparently for me.

**Comment by ryanflorence** [comment]
Thanks for the kind words.

> `onSubmit={this.handleSubmit.bind(this)}`

`React.createClass` autobinds methods, so you don't need that. PIT OF SUCCESS \o/

> `{ presets: ['es2015'] }`

https://github.com/reactjs/react-router-tutorial/blob/start/webpack.config.js#L11

**Comment by yormi** [comment]
Oh I used `class X extends React.Component` ...  sorry, my bad :P

For the preset thing, maybe I miss something again but I get when I do `npm start` :
```
ERROR in ./index.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/guillaume/Desktop"
    at /home/guillaume/Desktop/react-router-tutorial/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/guillaume/Desktop/react-router-tutorial/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/home/guillaume/Desktop/react-router-tutorial/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/home/guillaume/Desktop/react-router-tutorial/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.addConfig (/home/guillaume/Desktop/react-router-tutorial/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
    at OptionManager.findConfigs (/home/guillaume/Desktop/react-router-tutorial/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
    at OptionManager.init (/home/guillaume/Desktop/react-router-tutorial/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at File.initOptions (/home/guillaume/Desktop/react-router-tutorial/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/home/guillaume/Desktop/react-router-tutorial/node_modules/babel-core/lib/transformation/file/index.js:123:22)
 @ multi main
```

Cheers ;)

**Comment by garyfoo** [comment]
I am having the same error as well. Could someone help?

```
ERROR in ./index.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/garyfoo/Developer"
    at /Users/garyfoo/Developer/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:292:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/garyfoo/Developer/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:274:20)
    at OptionManager.mergePresets (/Users/garyfoo/Developer/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:263:10)
    at OptionManager.mergeOptions (/Users/garyfoo/Developer/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:248:14)
    at OptionManager.init (/Users/garyfoo/Developer/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:367:12)
    at File.initOptions (/Users/garyfoo/Developer/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/garyfoo/Developer/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/garyfoo/Developer/react-router-tutorial/lessons/01-setting-up/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/garyfoo/Developer/react-router-tutorial/lessons/01-setting-up/node_modules/babel-loader/lib/index.js:38:20)
 @ multi main
```
